---
title: "airquality"
output:
  html_document: default
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(visdat)
library(patchwork)

knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
ggplot2::theme_set(theme_bw())
```

# About `airquality`

This data set contains the daily air quality measurements in New York, May to September 1973.

```{r}
air_quality <- clean_names(airquality)
head(air_quality)
```

```{r}
dim(air_quality)
```

```{r}
colnames(air_quality)
```

```{r}
glimpse(air_quality)
```

# Exploratory Data Analysis

## Univariate non-graphical

```{r}
summary(air_quality)
```

```{r}
skimr::skim(air_quality)
```

## Univariate graphical

```{r}
vis_dat(air_quality)
```


```{r}
p1 <- ggplot(air_quality, aes(ozone)) +
  geom_histogram(color = "white")
p1
```

```{r}
p2 <- ggplot(air_quality, aes(solar_r)) +
  geom_histogram(color = "white")
p2
```

```{r}
p3 <- ggplot(air_quality, aes(wind)) +
  geom_histogram(color = "white")
p3
```

```{r}
p4 <- ggplot(air_quality, aes(temp)) +
  geom_histogram(color = "white")
p4
```


```{r}
(p1 + p2) / (p3 + p4)
```

```{r}
vis_cor(air_quality)
```


```{r}
air_quality <- air_quality %>% 
  mutate(
    date = lubridate::make_date(year = 1973, month = month, day = day) 
  )
air_quality
```

```{r}
air_quality %>% 
  summarize(sum(ozone < 0, na.rm = TRUE))
```


```{r}
ggplot(air_quality, aes(date, ozone)) +
  geom_line()
```

```{r}
ggplot(air_quality, aes(temp, ozone)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
# Simple linear regression imputation
air_quality_imputed <- simputation::impute_lm(air_quality, ozone ~ temp)
air_quality_imputed <- simputation::impute_lm(air_quality_imputed, solar_r ~ temp + ozone)
```

```{r}
# Random forest imputation
air_quality_imputed2 <- simputation::impute_cart(air_quality, ozone ~ temp + wind + date)
air_quality_imputed2 <- simputation::impute_cart(air_quality_imputed2, solar_r ~ ozone + temp + wind + date)
```

```{r}
vis_dat(air_quality_imputed)
```

```{r}
# ozone before and after imputation
before1 <- ggplot(air_quality, aes(temp, ozone)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Temperature (F)",
    y = "Ozone (ppb)",
    title = "Original"
  )

before2 <- ggplot(air_quality, aes(ozone)) +
  geom_histogram(aes(y = ..density..), color = "white") +
  geom_density(color = "red") +
  labs(
    x = "Ozone (ppb)"
  )

after1 <- ggplot(air_quality_imputed, aes(temp, ozone)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Temperature (F)",
    y = "Ozone (ppb)",
    title = "Simple Linear Regression imputed"
  )

after2 <- ggplot(air_quality_imputed, aes(ozone)) +
  geom_histogram(aes(y = ..density..), color = "white") +
  geom_density(color = "red") +
  labs(
    x = "Ozone (ppb)"
  )

(before1 + after1) / (before2 + after2)
```

Negative ozone levels after imputation

```{r, fig.width = 12, fig.asp = 0.618, out.width = "70%", fig.align = "center"}
after3 <- ggplot(air_quality_imputed2, aes(temp, ozone)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Temperature (F)",
    y = "Ozone (ppb)",
    title = "CART imputed"
  )

after4 <- ggplot(air_quality_imputed2, aes(ozone)) +
  geom_histogram(aes(y = ..density..), color = "white") +
  geom_density(color = "red") +
  labs(
    x = "Ozone (ppb)"
  )

patch <- (before1 / before2) | (after1 / after2) | (after3 / after4)  

ready <- patch + plot_annotation(
  title = "Comparing original to imputed data",
  subtitle = "Simple Linear Regression vs CART",
)
ready
```

```{r}
by_time <- ggplot(air_quality_imputed, aes(date, ozone)) +
  geom_line(color = "#5D8AA8")

by_month <- ggplot(air_quality_imputed, aes(date, ozone)) +
  geom_line() +
  facet_wrap(~lubridate::month(date, label = TRUE), scale = "free")

by_time / by_month
```
```{r}
by_time2 <- ggplot(air_quality_imputed2, aes(date, ozone)) +
  geom_line(color = "#5D8AA8")

by_month2 <- ggplot(air_quality_imputed2, aes(date, ozone)) +
  geom_line() +
  facet_wrap(~lubridate::month(date, label = TRUE), scale = "free")

by_time2 / by_month2
```

```{r}
ggplot(air_quality_imputed, aes(date)) +
  geom_line(aes(y = ozone), color = "red") +
  geom_line(data = air_quality, aes(y = ozone))
```

